enaml/fonts.py, examples/layout/advanced/button_ring.enaml
Make font parsing more flexible to order.  These now both work: `arial 12pt bold`, `12pt arial bold`.
Also corrected example that uses unsupported bare integer font size.
=> Fixes for font handling

enaml/qt/qt_object_combo.py
This fixes a bug where `editable` was not properly initialized by the backend ObjectCombo implementation.
=> Fix uninitialized `editable` attribute

tools/emacs/enaml.el
Advise python-indent-context to recognize enaml block forms. This is
something of a kludge, as it is difficult for derived modes to modify
indentation behavior in a comprehensive way. (See
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19908 for details).
It works for indentation, but other commands like
python-nav-beginning-of-block will only recognize Python-style blocks.
=> Improve indentation for Emacs mode

.travis.yml
This was not the case anymore because QScintilla pulls pyqt 5.9  from PyPI.
=> travis: test the version of qt5 available on conda

enaml/qt/qt_container.py, tests/test_layout_container.py
Previously when a widget was unparented from a QtContainer subclass the layout_container member was not cleared. This could lead to bugs when a relayout of the widget was requested as it would try to relayout its old parent.
If the new one is not a Container the member is not updated. Furthermore, the old  parent layout can be out of sync if it is not displayed at the time, which is turns can lead to an index error as a child appears missing.
I believe this fix is the cheapest one as it does not attempt to change the layout of the parent.
The test expose the bug before the fix and pass afterwards.
=> Fix issue #206 (layout_container member not cleared when unparenting)

enaml/core/code_tracing.py, enaml/src/dynamicscope.cpp, tests/test_comprehensions.py
This allow to properly trace list/dict/set comprehensions which use a function. As a consequence the tracer has to be accessible from the function in the comprehension. 
Rather than modifying the function to of the comprehension to accept the tracer as argument, I chose to adapt the loading opcode based on whether or not we are dealing with a nested code object. To work, this requires the tracer to appear in the local namespace which requires a tiny trick to make it appear in the locals of the dynamicscope. This will have a penalty cost in term of speed for the traced comprehension but I believe this is acceptable.
The alternative would be to modify the function involved in the comprehension when the comprehension is involved in tracing, by changing its argument and modifying how it is …
=> Trace nested code objects

enaml/layout/dock_layout.py, tests/test_dock_layout.py
Even if it is not clear why (I checked CPython sources but could not find why ), it appears that warn_explicit somehow corrupt the globals. Copying before reporting the warning appears to fix the error.
The tests can be used to investigate the bug.
Fixes #246
=> layout.dock_layout: fix call to explicit_warn

enaml/qt/qt_field.py, enaml/widgets/field.py, examples/widgets/field.enaml
I'm adding the `text_align` member on the `Field` widget, which takes a enum of `left` (default), `right` or `center`. This feature has been requested and discussed on #248 .
Short/minimal example also provided.
=> NEW: text_align allows to configure text alignment for Field

enaml/core/code_tracing.py, enaml/core/compiler_common.py, enaml/core/compiler_helpers.py, enaml/core/enaml_compiler.py, enaml/core/parser/base_parser.py, tests/test_inner_functions.py
Wrap functions defined inside operators or declarative function to call them with their scope of definition. This allows to handle properly comprehensions and lambdas (whose body is now properly traced). Also ensure that we compile the body of the :: operator as a function to properly handle closure.
Bump the compiler version to 26
I added tests for all the new behaviors
=> Fixes for closure in comprehensions and tracing of lambda functions

enaml/qt/qt_image_view.py, enaml/widgets/image_view.py
Previously if the image was made smaller than the image size, the size hint (which reflects the image size before rescaling) was used by the parent container which led to oversized container. This patch fixes this.
=> ImageView: Add constraints to enforce the respect of aspect ratio when required

README.rst
Just to correct the url used for Button Ring example
=> Fix typo in  hyper link

.appveyor.yml
Trying to send just a clean version, after fighting with GitHub.
Changes from #274: PySide is now run, but are allowed to fail without failing the build.
=> #272: Add CI Support for Windows - Attempt 2

docs/source/get_started/installation.rst
Based on recent experience as newbie, I have proposed a restructure of the Installation instructions.
* Clearly separate out the three methods.
* Make it clearer you can install without a C++ compiler on most platforms - pip install isn't much harder than Anaconda.
* Group the toolkit rendering libraries together and make recommendations clearer.
* Mention that you need to install QtPy (if doing it manually).
* Standardise on a command prompt ($ over C:\>, rather arbitrarily.)
=> Significant re-write to Installation instructions

examples/widgets/web_view.enaml, tests/test_dock_layout.py, tests/test_examples.py
Want to add an example for the WebView to note that the QtWebEngineWidgets must be imported before the QtApplication is started.  qtpy currently clobbers the import error that mentions this and it takes time to find this.  It's imported in the example so it works when using enaml-run.
Also added a test for dock interactions. I would like to also get it to cover the some of the drag and drop code but QTest doesn't seem to support this very well.
=> Add WebView example and another dock layout test

docs/source/dev_guides/index.rst, docs/source/dev_guides/languagebasedtools.rst, docs/source/get_started/introduction.rst, docs/source/index.rst
**Main Change**
There is a tools folder which is undocumented.  It contains various definitions for syntax-based tools so they can handle `.enaml` files.
This commit adds a new page to the Developer's Guide explaining how these definitions can be used in a long list of popular IDEs and also the Pygments lexer required for generating documentation.
**Bonus Extra**
Formatting, spelling and grammar improvements on a couple of the main RST files.
=> Add documentation for tools directory.

enaml/qt/qt_dialog.py, enaml/qt/qt_dock_item.py, enaml/qt/qt_main_window.py, enaml/qt/qt_window.py, enaml/widgets/close_event.py, enaml/widgets/dock_item.py, enaml/widgets/window.py, examples/widgets/dock_area.enaml
This will allow DockItem widgets to perform an action in response to the titlebar close button being clicked (and ignore this event if desired).
=> Add CloseEvent to DockItem

docs/source/dev_guides/index.rst, docs/source/get_started/index.rst
Currently, in the generated .pdf file, the toctree gets expanded before the reader's guide of the Getting Started chapter (i.e. the reader's guide ends up on pp. 18 and 19).
I'm not well-versed into sphinx, so I don't know if this change actually does fix that order...
=> Fix order of text in generated .pdf file

docs/source/api_ref/widgets/button_group.rst, docs/source/api_ref/widgets/index.rst, enaml/qt/qt_abstract_button.py, enaml/qt/qt_button_group.py, enaml/qt/qt_factories.py, enaml/widgets/abstract_button.py, enaml/widgets/api.py, enaml/widgets/button_group.py, examples/widgets/button_group.enaml, releasenotes.rst, tests/widgets/test_button_group.py
This is a proxy for Qt's QButtonGroup class, which allows manual
management of button groupings. This alleviates the restriction of
requiring all buttons to be within the same container to ensure that
only one button in the desired grouping can be selected at a time.
I don't think this is ready to merge in its current state. The
requirement to manually hook up the button to the button group in the
'activated' event handler is very clunky, but I'm not sure at present
of a better way of handling this.
I'm also not sure that it makes sense to have the button group as an
actual widget, but I wasn't sure of a better way to handle this either.
The Timer widget (a proxy for the QTimer class) appears to work in the
same way that this patch currently does.
I'm pretty sure there is some other …
=> Add button group widget

enaml/qt/qt_field.py, releasenotes.rst
Fixing issue with validator fields, where clearing the error state does not restore the original stylesheet
=> Fixing issue with validator fields

enaml/core/parser/base_lexer.py, enaml/core/parser/base_parser.py
This implements the solution 2 outlines in #380. Except for the need to manually filter out possibly wrong nodes this looks reasonably clean to me.
Existing tests pass but we probably need some extra ones.
=> parser: allow alias and const not to be keywords

enaml/qt/docking/q_dock_tab_widget.py, enaml/widgets/dock_item.py, releasenotes.rst
initFrom was removed and we need to do its job manually. Still need to manually set the pen and background but it already seems to be working.
Closes #395
=> qt: fix q_dock_tab_widget for PyQt5

enaml/core/import_hooks.py, releasenotes.rst, tests/core/test_importer.py, tests/core/test_zipimporter.py
The migration to Python 3 messed up the setting of the attributes on the module (\_\_file\_\_ in particular) this fixes it cleanly and add tests.
=> core: ensure that module attributes are properly set

.github/workflows/ci.yml, .travis.yml, enaml/src/declarative_function.cpp, enaml/version.py, releasenotes.rst, tests/core/test_declarative_function.py
This fixes a bug identified in https://github.com/nucleic/enaml/pull/348, which boils down to a reference counting issue in declarative function that led to the deletion of the builtins dictionary.
=> Declarative function reference counting issue

enaml/core/parser/base_lexer.py, enaml/core/parser/base_parser.py, enaml/core/parser/parser35.py, examples/widgets/dates.enaml, tests/core/test_operators.py
=> Add subscription block

docs/source/get_started/syntax.rst, enaml/compat.py, enaml/core/code_generator.py, enaml/core/code_tracing.py, enaml/core/compiler_common.py, enaml/core/enaml_compiler.py, enaml/core/parser/base_parser.py, enaml/core/parser/parser3.py, enaml/core/parser/parser38.py, enaml/core/standard_inverter.py, enaml/core/standard_tracer.py, examples/widgets/image_view.enaml, releasenotes.rst, tests/core/parser/test_return.py, tests/core/parser/test_walrus.py, tests/core/parser/test_yield.py, tests/core/test_operators.py
This covers the walrus operator := and the use of * in return and yield
=> Add support for missing Python 3.8 features

enaml/qt/qt_application.py, releasenotes.rst
The argument to QApplication is used to set the application name. On Linux (Xorg) this can be queried using the xprop utility. Specifically, this name will be used for the ``WM_CLASS`` property [1], which can be used by X-based window managers to manipulate window placement and app-specific behaviour (automatic floating, tiling, positioning, etc). The approach proposed here is used by Jupyter's QtConsole [2] for example.
[1] https://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS
[2] jupyter/qtconsole#16
This is only for the Qt backend.. I'm not familiar with the other frameworks.
=> Allow to explicitly set Qt application name

docs/source/get_started/installation.rst, enaml/version.py, releasenotes.rst, setup.py
This allows to avoid polluting the enaml install while still providing a nice way to access the qt backend.
=> setup: add extras_require to allow to easily install Qt

tools/vim/syntax/enaml.vim
This fixes spurrious highlighting of characters immediately preceding
or following an enamlOperator. Also, the case of the notification
operator `::` followed by and EOL is now handled correctly. Lastly, the
`attr` keyword is highlighted using the Define group (like python
decorators, etc.)
=> Minor fixes to vim syntax highlighting

examples/applib/live_editor.enaml, releasenotes.rst
Closes #436
Any error occurring will be redirected to the error pane, and the editor remain live. 
Note that the same approach should not be used in a general app since raising in a handler can leave the app in a corrupted state.
=> examples: prevent crash if executing a handler in the editor raises

enaml/core/compiler_common.py, releasenotes.rst, tests/conftest.py, tests/test_inner_functions.py
Template instance operator binding require some extra work compared to conventional operator binding since we need both the node where the template is instantiated and where it is defined. However the analysis of globals and comprehensions performed for standards operators apply but was not carried out previously. This bug has been there for quite some time and was likely introduced when migrating to Python 3.
This needs tests before it can be merged.
=> Fix template instance operator binding.

enaml/qt/q_flow_layout.py, releasenotes.rst, tests/test_flow_layout.py
Potential fix for issue mentioned in https://github.com/nucleic/enaml/issues/447
```
<class 'TypeError'>
'<' not supported between instances of 'QFlowWidgetItem' and 'QFlowWidgetItem'
```
Dont rely on Python's sort; we should not include the QFlowWidgetItem in the sort key.
Disclaimer -  I had some issues running tests locally (had to start a whole new fresh python/venv environment but I'm not convinced I did it 100% correctly) so I *think* this test is OK.
=> Flow Layout sort fix for stretch or ortho_stretch > 0

.github/workflows/ci.yml, enaml/compat.py, enaml/core/code_generator.py, enaml/core/enaml_compiler.py, releasenotes.rst, tests/core/test_code_generator.py
In Python <3.10+, we were sure to find a single implicit return None per python block. Starting with 3.10, the implicit return None in with or try/except can be duplicated rather than being behind a jump. So we identify all explicit return None in the AST and prune implicit return None from all blocks in the bytecode control flow graph.
=> core: prune return None from inserted Python blocks

enaml/qt/docking/dock_overlay.py, enaml/qt/docking/q_guide_rose.py, releasenotes.rst
PyQt 5.15.6 may have deprecated some overloaded methods and methods and constructors no longer appear to accept floats. This fixes #472.
=> Ensure pixel dimensions remain integer

enaml/qt/docking/dock_manager.py, enaml/qt/docking/q_dock_container.py, enaml/qt/docking/q_dock_placeholder.py, enaml/qt/docking/q_dock_tab_widget.py, enaml/qt/docking/q_dock_title_bar.py, enaml/qt/docking/q_dock_window.py, enaml/qt/qt_dock_item.py, enaml/widgets/dock_item.py, examples/widgets/dock_area.enaml, releasenotes.rst
While investigating and fixing #467, I found a bunch of other issues that this PR addresses along with #467.
I do not have time to wind up the unit tests this deserves so I would appreciate if anybody can stress test this is a bit before merging. Each commit addresses a specific issue and can be reviewed independently. Hopefully commit messages are clear.
=> Dock area fixes

.appveyor.yml, enaml/core/code_generator.py, releasenotes.rst, tests/core/test_code_generator.py
This is missing a test but should otherwise be good.
=> core: avoid generating empty block when trimming bytecode blocks

enaml/qt/q_deferred_caller.py
PyQt seems to not do any more casting.. This was reported on the inkcut forum https://inkcut.org/t/it-isnt-inkcut/104/post/381/ and I was able to reproduce it.
=> Coerce QTimer.singleShot ms argument to int

.github/workflows/ci.yml, enaml/qt/Qsci.py, enaml/qt/__init__.py, enaml/qt/docking/q_icon_widget.py, enaml/qt/qt_scintilla.py, enaml/qt/scintilla_lexers.py, examples/applib/live_editor.enaml
Builds on #475. It seems like PyQt6 changes how enums values are exposed.  
One fix in q_icon_widget that may need addressed https://doc-snapshots.qt.io/qt6-dev/qlayout.html#getContentsMargins seems to have moved from QWidget.
=> Update scintilla for Qt6

enaml/qt/compat.py, enaml/qt/docking/__init__.py, enaml/qt/docking/layout_builder.py, enaml/qt/docking/q_dock_frame.py, enaml/qt/docking/q_dock_tab_widget.py, enaml/qt/docking/q_dock_window.py, enaml/qt/q_popup_view.py, enaml/qt/qt_date_selector.py, enaml/qt/qt_time_selector.py
I discovered all of these issues when testing with the desktop example. 
I have started testing against my application (psiexperiment) and may have more to report later.
=> Enaml qt6 fixes (for deprecated methods)

docs/source/examples/ex_grid.rst, enaml/qt/q_popup_view.py, enaml/qt/qt_action.py, enaml/qt/qt_dock_area.py, enaml/qt/qt_dock_item.py, enaml/qt/qt_dock_pane.py, enaml/qt/qt_flow_area.py, enaml/qt/qt_flow_item.py, enaml/qt/qt_notebook.py, enaml/qt/qt_page.py, enaml/qt/qt_split_item.py, enaml/qt/qt_stack_item.py, enaml/qt/qt_tool_bar.py, enaml/styling.py, enaml/widgets/mpl_canvas.py, enaml/widgets/vtk_canvas.py, examples/workbench/crash_course.rst
There are small typos in:
- docs/source/examples/ex_grid.rst
- enaml/qt/q_popup_view.py
- enaml/qt/qt_action.py
- enaml/qt/qt_dock_area.py
- enaml/qt/qt_dock_item.py
- enaml/qt/qt_dock_pane.py
- enaml/qt/qt_flow_area.py
- enaml/qt/qt_flow_item.py
- enaml/qt/qt_notebook.py
- enaml/qt/qt_page.py
- enaml/qt/qt_split_item.py
- enaml/qt/qt_stack_item.py
- enaml/qt/qt_tool_bar.py
- enaml/styling.py
- enaml/widgets/mpl_canvas.py
- enaml/widgets/vtk_canvas.py
- examples/workbench/crash_course.rst
Fixes:
- Should read `underlying` rather than `underyling`.
- Should read `dependency` rather than `dependecy`.
- Should read `notify` rather than `notifiy`.
- Should read `frameless` rather than `framless`.
- Should read `extended` rather than `extened`.
- Should read `contiguous` rather than …
=> docs: Fix a few typos

enaml/qt/q_popup_view.py
For #499. This disables the on screen checks to fix weird positioning of popups on X11 when multiple displays are present. Tested with QT 5.15 and 6.3.1 with 2 and 3 FHD monitors in a horizontal row.
The desktop notification of the popup example is still showing on the primary desktop.  
If anyone else is able to test it would be appreciated.
=> Workaround multi-display issues on X11 with popups

.coveragerc, enaml/qt/docking/dock_images/__init__.py, enaml/qt/docking/q_guide_rose.py, tests/qt/test_dock_area_images_loading.py
We test directly the loading since we cannot test D&D on the dock area
This is extremely annoying and I will do my best to release a patch version ASAP
=> qt: fix loading dock images

enaml/core/compiler_helpers.py, releasenotes.rst
I reverted d47be167 that requires the development branch of atom which is not ready for a new release.
=> Prepare release 0.15.2

tools/pygments/pygments_enaml/lexer.py, tools/pygments/pyproject.toml
This makes it highlight func's like normal def's
Before
After
=> pygments lexer: Add enaml func expression

enaml/src/declarative_function.cpp, releasenotes.rst, tests/core/test_declarative_function.py
Currently if you use observe with a decl func it is impossible to remove the observer unless you clear all observers. This fixes that. 
A simple example to show the problem.  
```python
from atom.api import Atom, Str
from enaml.widgets.api import Window, Container, Label, Field, PushButton
class Model(Atom):
output = Str()
enamldef Main(Window): window:
attr model = Model()
func decl_print(x):
print(x)
Container:
PushButton:
text = "Add observer"
clicked :: model.observe("output", decl_print)
PushButton:
text = "Remove observer"
clicked :: model.unobserve("output", decl_print)
Field:
submit_triggers = ["auto_sync"]
text := model.output
```
The hash function is based on cpythons method_hash (see https://github.com/python/cpython/blob/81f7359f67a7166d57a10a3d5366406d9c85f1de/Objects/classobj …
=> Implement hash and eq for bound decl func

development.rst, enaml/core/parser/base_python_parser.py, enaml/core/parser/enaml_parser.py, pyproject.toml, releasenotes.rst, tests/conftest.py, tests/core/parser/test_parser.py
See #529 for details. Note that the unit tests I added do not actually capture the bug for some reason, but I can verify that in my own code (where I discovered the bug), the changes I made to raising SyntaxError solves the issue.
=> Enaml syntaxerror detail

enaml/core/code_generator.py, releasenotes.rst, tests/test_template.py
Adds a few isinstance checks needed in rewrite_fast_locals on python 3.12. Fixes #548
=> Fix potential error in rewrite fast locals on 3.12 for #548

enaml/core/standard_tracer.py, enaml/src/subscription_observer.cpp, releasenotes.rst, setup.py, tests/core/test_subscription_observer.py
Moves the subscription observer in standard_tracer.py to cpp. 
This gives a considerable performance increase if there are a lot of changes going on (~60%) but for most code it will likely only be a small improvement. My application sped up about 30% (even after fixing the original problem).
Ref https://github.com/nucleic/enaml/issues/561
=> Move standard_tracer's subscription observer to cpp

enaml/src/funchelper.cpp, tests/core/test_funchelper.py
All of the argument types are already checked so it is safe to use the faster variant.
=> Update funchelper call_func

enaml/core/dynamicscope.py, enaml/src/dynamicscope.cpp, setup.py, tests/core/test_dynamicscope.py
It is not very efficient to the use of dir() and a set to track used keys... but makes python 3.12+ provide useful messages for name errors and attribute errors. 
I'd like to add more tests after any initial feedback.
Eg:
```python
enamldef Main(Window): window:
Container:
PushButton:
text = "Click me!"
clicked :: print(windo.size())
```
Gives `NameError: name 'windo' is not defined. Did you mean: 'window'?`
From looking at the traceback source code it ignores giving suggestions if there are > 750 items (https://github.com/python/cpython/blob/main/Lib/traceback.py#L1465). Which I can see it easily exceeding.. So it might be good to also skip globals and builtins?
=> Add a proper dynamicscope iterator

enaml/core/dynamicscope.py
The `yield from` feature of Python 3 makes this cleaner.
I didn't test locally. Let's see what the CI tests show.
=> Use yield from instead of chained iterables

enaml/core/import_hooks.py
Using the cache_tag from sys.implementation over manually creating a similar tag has the advantage, that it can correctly distinguishes between different python implementations.
=> import_hooks: Use cache_tag from PEP 421
