nucleic/enaml

examples/functions/declare_function.enaml
examples/functions/observe_model_signal.enaml
examples/functions/override_function.enaml
examples/layout/advanced/override_layout_constraints.enaml

This adds some examples on how to use declarative functions. Some examples are not very inspired but at least they show how things work. I would like to add a fourth one so this is not ready to merge. But feel free to review what is already there.

Declarative function examples

---

tools/barebones/Enaml.plist

To install with TextWrangler, copy to: `~/Library/Application Support/TextWrangler/Language Modules/`
See http://www.barebones.com/support/develop/clm.html for more details.

Add a syntax definition for BBEdit/TextWrangler

---

enaml/qt/qt_object_combo.py

qtobjectcombo : stops timer when calling destroy.

---

enaml/core/import_hooks.py

closes #202 
This fixes the issue for me. Should I add a test for it ?
Note : would you consider making a 0.9.9 release for the small bugs that were fixed over the past months ?

Remove module from sys.modules when an exception occurs

---

enaml/workbench/workbench.py
setup.py

This was left unresolved. Except for the unnecessary white spaces it looks good. @frmdstryr perhaps you could fix it so that @sccolbert could merge (if he agrees with me).

Fix :  Use Include/Looper in PluginManifest's #193 

---

README.rst
docs/source/examples/ex_focus_traversal.rst
docs/source/get_started/syntax.rst
examples/widgets/buttons.enaml
examples/widgets/focus_traversal.enaml

Minor improvements to the readme.rst.

Readme.rst fixes

---

.travis.yml
examples/workbench/sample.py
tests/test_compileall.py
tests/test_workbench.py
tests/utils.py

Refactored the enaml_run to use https://docs.pytest.org/en/latest/monkeypatch.html and moved it to tests/utils.py

Add test for workbench example

---

examples/tutorial/employee/employee.py

I tried it with the updated function name and it works. Not sure if I'd need to do anything else.

examples: update observer function name so it gets picked up by Atom

---

examples/tutorial/employee/employee.py

Use a more accurate outcome for age.
Remaining issue: the program still crashes when dob > now

Improve age calculation

---

docs/source/examples/tut_employee.rst

docs: add download link for phone validator in employee tutorial

---

docs/source/cmd_ref/index.rst
docs/source/index.rst

Add "Command Reference" to docs

---

.travis.yml
enaml/qt/qt_field.py
enaml/widgets/field.py

@sccolbert this is one way to address #352 that seems minimally invasive. WDYT ?

widgets: add sync_time attribute to Field

---

enaml/core/parser/__init__.py
enaml/core/parser/base_parser.py
enaml/core/parser/parser36.py
releasenotes.rst
tests/core/parser/test_f_strings.py

Closes #377 
This requires tests and release notes updates

Improve error reporting on invalid syntax for f-strings

---

enaml/image.py

image: clarify how to handle base64 images

---

enaml/qt/docking/q_dock_container.py
releasenotes.rst
tests/test_dock_layout.py

Avoid going higher than the top dock area when looking for a DockTabWidget

---

enaml/qt/docking/q_dock_tab_widget.py

Fix simple typo: visibilty -> visibility

---

enaml/src/dynamicscope.cpp
releasenotes.rst
tests/core/test_dynamicscope.py

For #376 also (hit in #393)
Please review, still not the best with cpp

Add get to dynamicscope

---

enaml/qt/qt_widget.py
releasenotes.rst
tests/widgets/test_focus_tracker.py
tests/widgets/test_focus_traversal.py

fixed return value of QtWidget.tab_focus_request() and added release note entry

---

enaml/core/looper.py
releasenotes.rst
tests/core/test_looper.py

For #414. 
Not sure if there's a better way to do this.

Coerce a Loopers iterable to an tuple if it is an iterator

---

.github/workflows/ci.yml
enaml/src/callableref.cpp
enaml/src/signaling.cpp
enaml/src/weakmethod.cpp
enaml/version.py
releasenotes.rst
tests/test_callableref.py
tests/test_signaling.py
tests/test_weakmethod.py
tests/test_winutil.py

Also add tests for winutil extension

Fix signaling/weakmethod/callableref and add tests

---

.appveyor.yml
.github/workflows/ci.yml
README.rst
docs/source/get_started/installation.rst
enaml/qt/QtCore.py
enaml/qt/__init__.py
enaml/qt/docking/q_dock_tab_widget.py
enaml/qt/docking/q_text_label.py
enaml/qt/q_popup_view.py
enaml/qt/q_window_base.py
enaml/qt/qt_dialog.py
enaml/qt/qt_scintilla.py
enaml/qt/qt_window.py
enaml/qt/scintilla_lexers.py
enaml/stdlib/dialog_buttons.enaml
releasenotes.rst
tests/conftest.py
tests/core/parser/test_async.py

Qt 5.15 started to mark as obsolete a number of feature related to Screen detection. We use the new alternative that remain compatible with qt 5.9+.

Add support for Pyside2 and avoid using deprecated API

---

docs/source/get_started/installation.rst

Fix undocumented depencies

---

enaml/core/parser/base_parser.py
enaml/core/parser/parser39.py
releasenotes.rst

python3.9 was broken due to missing import.

Fix python3.9 support

---

enaml/qt/qt_notebook.py
enaml/qt/styleutil.py
examples/styling/notebook.enaml
releasenotes.rst

I couldn't figure out how to style notebook tabs? 
If there's already a way to do it please close this.

Add support for notebook tab styling

---

.github/workflows/ci.yml
enaml/core/import_hooks.py
enaml/drag_drop.py
enaml/layout/strength_member.py
enaml/qt/docking/q_dock_bar.py
enaml/qt/q_popup_view.py
enaml/qt/qt_drag_drop.py
enaml/qt/qt_notebook.py
enaml/qt/qt_stack.py
enaml/qt/qt_widget.py
enaml/version.py
enaml/widgets/dock_events.py
enaml/widgets/widget.py
releasenotes.rst

This should make enaml compatible with latest atom.

Use enum.IntEnum/IntFlag rather than atom.IntEnum

---

.github/workflows/docs.yml
docs/requirements.txt
readthedocs.yml

Because I do not own the nucleic org I cannot get rtd feedback on PR but I enabled PR building on RTD, so we can at least check things are fine.

rtd: fix build configuration

---

enaml/qt/scintilla_tokens.py
releasenotes.rst

QsciLexerPython has tokens for fstrings now.

Add python fstring scintilla tokens

---

.github/workflows/ci.yml
.github/workflows/release.yml
enaml/qt/__init__.py
enaml/qt/compat.py
enaml/qt/docking/dock_resources.py
enaml/qt/docking/event_types.py
enaml/qt/docking/q_bitmap_button.py
enaml/qt/docking/q_dock_container.py
enaml/qt/docking/q_dock_tab_widget.py
enaml/qt/docking/q_dock_title_bar.py
enaml/qt/docking/q_dock_window.py
enaml/qt/docking/q_text_label.py
enaml/qt/q_deferred_caller.py
enaml/qt/q_flow_layout.py
enaml/qt/q_resource_helpers.py
enaml/qt/qt_dual_slider.py
enaml/qt/qt_mpl_canvas.py
enaml/qt/qt_slider.py
examples/widgets/focus_traversal.enaml
releasenotes.rst
setup.py
tests/test_examples.py
tests/widgets/test_focus_tracker.py

Qt6 support

---

.gitignore
enaml/qt/q_flow_layout.py
releasenotes.rst
tests/widgets/test_flow_area.py

This is missing a test currently

qt: fix flow layout calculation on Qt6

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
enaml/core/compiler_helpers.py

core: use atom.add_member to add members after a class is defined

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
enaml/qt/q_flow_layout.py
enaml/widgets/dock_area.py
releasenotes.rst

address https://github.com/nucleic/enaml/pull/496#issuecomment-1192061589

Reimplement DockArea.initialize instead of shadowing the initialized member

---

examples/tutorial/employee/employee.py
examples/tutorial/hello_world/hello_world.py
examples/tutorial/person/person.py
examples/workbench/sample.py

Some examples requires it somehow

Fix default module path

---

examples/tutorial/async/async.py
examples/tutorial/async/async_view.enaml

For #510 . A similar approach can be used with other qt / asyncio libraries.

Add async example
